### ISSUE TITLE
Add some action hooks for theme/plugin integration and devs

### ISSUE THREAD

**Issue by deckerweb** [brainstormforce/bsf-docs#29]
I suggest adding a few hooks here and there in the packaged template files. This would avoid fiddling with templates in the theme (I like it lean and clean). Some action hooks would be enough.

The first one I suggest is for breadcrumb functionality - just after your existing Yoast Breadcrumb integration.
something like: do_action( 'bsf_docs_after_doc_title' );

I added this manually in my project and working fine - currently juse Justin Tadlocks "Breadcrumb Trail" with it - perfect :)

I could do this as a Pull Request also if you're fine with that? ;-)

**Comment by pratikchaskar** [comment]
Thank you for suggestion David!

We appreciate your contribution & happy to accept your Pull Request. Please send it. :)

**Comment by deckerweb** [comment]
Awesome, thank you! Will add it soon :)
